services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: solidarity-sqlserver    
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Solidarity@123"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Solidarity@123", "-Q", "SELECT 1", "-C"]
      interval: 20s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  mongodb:
    image: mongo:8
    container_name: solidarity-mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: solidarity-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 20s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Solidarity.Api/Dockerfile
    container_name: solidarity-api
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Solidarity.Worker/Dockerfile
    container_name: solidarity-worker
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped