apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-data-pvc
  namespace: solidarity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data-pvc
  namespace: solidarity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
  namespace: solidarity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
