apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: solidarity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "Solidarity@123"
          volumeMounts:
            - name: sqlserver-data
              mountPath: /var/opt/mssql
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: sqlserver-data
          persistentVolumeClaim:
            claimName: sqlserver-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: solidarity
spec:
  selector:
    app: sqlserver
  ports:
    - name: sql
      protocol: TCP
      port: 1433
      targetPort: 1433
